spring:
  profiles:
    active: local
  mail:
    host: smtp.gmail.com
    port: 587
    username: placeholder
    password: placeholder
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  mail:
    from: placeholder
    name: FixPoint

google:
  client-id: placeholder

jwt:
  secret: ${JWT_SECRET:fixpoint_super_secret_key_must_be_at_least_256_bits_long_for_hs256}
  expiration: ${JWT_EXPIRATION:86400000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}